# Generated by Django 4.1.7 on 2023-03-26 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[("carted", "carted"), ("purchased", "purchased")],
                default="carted",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100, null=True)),
                ("post", models.CharField(max_length=100, null=True)),
                ("pin", models.IntegerField(null=True)),
                ("quantity", models.IntegerField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("carted", "carted"), ("purchased", "purchased")],
                        default="purchased",
                        max_length=100,
                    ),
                ),
                (
                    "mobile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="m_purchase",
                        to="store.products",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="u_purchase",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
